"""walking_route

Revision ID: 1416e17fd7d7
Revises: 38cf92c3837a
Create Date: 2025-10-01 18:19:56.882649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1416e17fd7d7'
down_revision: Union[str, Sequence[str], None] = '38cf92c3837a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walking_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('points_of_interest_count', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_walking_routes_id'), 'walking_routes', ['id'], unique=False)
    op.create_index(op.f('ix_walking_routes_title'), 'walking_routes', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_walking_routes_title'), table_name='walking_routes')
    op.drop_index(op.f('ix_walking_routes_id'), table_name='walking_routes')
    op.drop_table('walking_routes')
    # ### end Alembic commands ###
