"""photo_event

Revision ID: 1546acb9ecdf
Revises: c8e0760bd79e
Create Date: 2025-10-02 12:36:29.847762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1546acb9ecdf'
down_revision: Union[str, Sequence[str], None] = 'c8e0760bd79e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('has_photo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'has_photo')
    # ### end Alembic commands ###
