"""photo_event

Revision ID: 26d1cb93aa26
Revises: 0cdf5313b5e3
Create Date: 2025-10-02 12:59:51.558133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d1cb93aa26'
down_revision: Union[str, Sequence[str], None] = '0cdf5313b5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_verified')
    op.drop_column('events', 'has_photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('has_photo', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
