"""Update RequestStatus enum to lowercase

Revision ID: 27290b10569a
Revises: aaa59b19ca6b
Create Date: 2025-10-02 15:37:39.947721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27290b10569a'
down_revision: Union[str, Sequence[str], None] = 'aaa59b19ca6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
