"""comint_in_obshaga

Revision ID: 28c85ba7df1d
Revises: 1fd60a3dbcd9
Create Date: 2025-10-02 11:24:14.107169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c85ba7df1d'
down_revision: Union[str, Sequence[str], None] = '1fd60a3dbcd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
