"""test3

Revision ID: 3fa47a4bd05b
Revises: fb8de9a09751
Create Date: 2025-09-27 09:48:13.071193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa47a4bd05b'
down_revision: Union[str, Sequence[str], None] = 'fb8de9a09751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passwordQWE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwordQWE', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
