"""user

Revision ID: 4733df6d9e31
Revises: d28c8aec7e82
Create Date: 2025-10-01 18:03:35.032298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4733df6d9e31'
down_revision: Union[str, Sequence[str], None] = 'd28c8aec7e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
