"""Update RequestStatus enum to lowercase

Revision ID: 6a43cbf729cb
Revises: 27290b10569a
Create Date: 2025-10-02 15:40:35.129403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a43cbf729cb'
down_revision: Union[str, Sequence[str], None] = '27290b10569a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walking_routes', sa.Column('url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('walking_routes', 'url')
    # ### end Alembic commands ###
