"""photo_event

Revision ID: 84e6c5d1bca7
Revises: f3b195a17ad8
Create Date: 2025-10-02 13:06:13.044080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e6c5d1bca7'
down_revision: Union[str, Sequence[str], None] = 'f3b195a17ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description_summ', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'description_summ')
    # ### end Alembic commands ###
