"""user

Revision ID: 8acac9bea2e8
Revises: a23a76baa371
Create Date: 2025-10-01 16:58:45.768289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8acac9bea2e8'
down_revision: Union[str, Sequence[str], None] = 'a23a76baa371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('consecutive_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'consecutive_days')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
