"""Update RequestStatus enum to lowercase

Revision ID: aaa59b19ca6b
Revises: 1930ea055ec8
Create Date: 2025-10-02 15:34:59.556276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa59b19ca6b'
down_revision: Union[str, Sequence[str], None] = '1930ea055ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
