"""test3

Revision ID: cd671efea06c
Revises: e6857916f1a6
Create Date: 2025-10-01 15:32:29.257545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd671efea06c'
down_revision: Union[str, Sequence[str], None] = 'e6857916f1a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memorial_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memorial_dates_date'), 'memorial_dates', ['date'], unique=False)
    op.create_index(op.f('ix_memorial_dates_id'), 'memorial_dates', ['id'], unique=False)
    op.create_table('scenic_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('spot_type', sa.Enum('PARK', 'ESTATE', 'CASTLE', 'MONUMENT', 'NATURAL', 'HISTORICAL', 'ARCHITECTURAL', 'RELIGIOUS', name='spottype'), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('opening_hours', sa.String(length=100), nullable=True),
    sa.Column('entrance_fee', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenic_spots_address'), 'scenic_spots', ['address'], unique=False)
    op.create_index(op.f('ix_scenic_spots_id'), 'scenic_spots', ['id'], unique=False)
    op.create_index(op.f('ix_scenic_spots_spot_type'), 'scenic_spots', ['spot_type'], unique=False)
    op.create_index(op.f('ix_scenic_spots_title'), 'scenic_spots', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenic_spots_title'), table_name='scenic_spots')
    op.drop_index(op.f('ix_scenic_spots_spot_type'), table_name='scenic_spots')
    op.drop_index(op.f('ix_scenic_spots_id'), table_name='scenic_spots')
    op.drop_index(op.f('ix_scenic_spots_address'), table_name='scenic_spots')
    op.drop_table('scenic_spots')
    op.drop_index(op.f('ix_memorial_dates_id'), table_name='memorial_dates')
    op.drop_index(op.f('ix_memorial_dates_date'), table_name='memorial_dates')
    op.drop_table('memorial_dates')
    # ### end Alembic commands ###
