"""test2

Revision ID: fb8de9a09751
Revises: 9dd4f3b9001f
Create Date: 2025-09-27 09:47:54.157350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb8de9a09751'
down_revision: Union[str, Sequence[str], None] = '9dd4f3b9001f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwordQWE', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passwordQWE')
    # ### end Alembic commands ###
