"""email_user

Revision ID: fbfb93d22f04
Revises: bf8a1256ca17
Create Date: 2025-10-02 15:03:55.623606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbfb93d22f04'
down_revision: Union[str, Sequence[str], None] = 'bf8a1256ca17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('representation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_representation_requests_id'), 'representation_requests', ['id'], unique=False)
    op.create_index(op.f('ix_representation_requests_status'), 'representation_requests', ['status'], unique=False)
    op.create_index(op.f('ix_representation_requests_user_id'), 'representation_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_representation_requests_user_id'), table_name='representation_requests')
    op.drop_index(op.f('ix_representation_requests_status'), table_name='representation_requests')
    op.drop_index(op.f('ix_representation_requests_id'), table_name='representation_requests')
    op.drop_table('representation_requests')
    # ### end Alembic commands ###
